{% set name = "dbus-python" %}
{% set version = "1.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11238f1d86c995d8aed2e22f04a1e3779f0d70e587caffeab4857f3c662ed5a4
  patches:
    - osx-arm64-dynamic_lookup.patch  # [osx and arm64]
    - no-dbus_py_test.patch  # [build_platform != target_platform]

build:
  number: 3
  skip: true  # [win]
  script:
    - cp $BUILD_PREFIX/share/gnuconfig/config.* ./build-aux  # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
    - make  # [unix]
    - pkg-config  # [unix]
    # extras for cross-compilation
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - dbus
    - glib
    - pip >=21.3
    - python
    - setuptools
  run:
    - dbus
    - python

test:
  imports:
    - dbus
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check

about:
  home: http://www.freedesktop.org/wiki/Software/DBusBindings/#python
  dev_url: https://gitlab.freedesktop.org/dbus/dbus-python
  doc_url: https://dbus.freedesktop.org/doc/dbus-python/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python bindings for dbus
  description: |
     D-Bus is a message bus, used for sending messages between applications.
     Conceptually, it fits somewhere in between raw sockets and CORBA in
     terms of complexity.

     This package provides a Python interface to D-Bus.

     See the dbus description for more information about D-Bus in general.

extra:
  recipe-maintainers:
    - duncanmmacleod
